### ISSUE TITLE
Add a "create MN..." button like some other PoS/MN wallets

### ISSUE THREAD

**Issue by esavard** [LunariumCoin/lunarium#15]
Also, there is add, delete, update (edit?) buttons that could be useful to reproduce in Lunarium wallet.

**Comment by esavard** [comment]
Also, there is add, delete, update (edit?) buttons that could be useful to reproduce in Lunarium wallet.

**Comment by jackkdev** [comment]
Task completed:

https://github.com/LunariumCoin/lunarium/commit/f316bc80b3abdb73fb606356bae54fbc8933fe69
