### ISSUE TITLE
Remove Anonymizaton and automint from unlock screen

### ISSUE THREAD

**Issue by RealHoneyBadger** [LunariumCoin/lunarium#24]
Until zerocoin feature possibly is reintroduced this text should be removed.

![capture](https://user-images.githubusercontent.com/38737396/45262113-8f36a680-b410-11e8-8518-0c642b2e87f1.PNG)

**Comment by jackkdev** [comment]
Sorted here:
https://github.com/LunariumCoin/lunarium/pull/27
