### ISSUE TITLE
Wallet stop staking after a while

### ISSUE THREAD

**Issue by esavard** [LunariumCoin/lunarium#28]
On Raspberry Pi and Windows, the wallet staking works for a couple of hours then stops. Seems to happen on Linux Desktop, but less frequently.

Message in the debug.log file when that happens:

`018-09-20 21:59:06 ThreadStakeMinter() exception 
2018-09-20 21:59:06 ThreadStakeMinter exiting,
2018-09-20 21:59:06 ProcessNewBlock : ACCEPTED in 4172 milliseconds with size=461
2018-09-20 21:59:06 stakemint thread exit`

The message comes from this line of code: https://github.com/LunariumCoin/lunarium/blob/f05b3679ff4b89fce712b4603718403a57d98f8b/src/net.cpp#L1581

Memory, process and disk utilization seem normal when the bug occurs.

PIVX seems to have fix the problem with:

* https://github.com/PIVX-Project/PIVX/issues/427
* https://github.com/PIVX-Project/PIVX/commit/2b896d18360ce917c61a36e9f90e67eb3f6d36a4

We should try to apply that fix to Lunarium code base, and run some tests to see if it fixes this issue.

**Comment by jackkdev** [comment]
https://github.com/LunariumCoin/lunarium/pull/29

**Comment by esavard** [comment]
Dupplicate of #29. Closing this issue.
